[package]
name = "ssrf_003_good_reqwest"
version = "0.1.0"
edition = "2021"

[dependencies]
iron = "0.6.1"
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.12", features = ["blocking"] }