[package]
name = "ssrf_002_bad_reqwest_client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
warp = "0.3"
reqwest = { version = "0.12", features = ["json"] }