[package]
name = "hardcoded_secret_bad_06_camellia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
camellia = "0.1.0"